on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  linux-build:
    name: Build and test on Linux
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: alire-project/setup-alire@v5

    - name: Alire build
      run: alr build

    - name: Test Build
      run: |
        cd tests/
        alr build
        
    - name: SPARK proof
      run: |
        cd tests/
        alr gnatprove -j0 --level=4 --checks-as-errors -cargs -gnatef > output.txt 2>&1 || status=$?

    - run: ./tests/obj/main_offsets
    - run: ./tests/obj/main_buffer
    - run: ./tests/obj/main_framed
